#pragma once
#define	MOVIELOADER_CUBE_FRONT		0	//!< CUBE_FRONT
#define	MOVIELOADER_CUBE_REAR		1	//!< CUBE_REAR
#define	MOVIELOADER_CUBE_LEFT		2	//!< CUBE_LEFT
#define	MOVIELOADER_CUBE_RIGHT		3	//!< CUBE_RIGHT
#define	MOVIELOADER_CUBE_TOP		4   //!< CUBE_TOP
#define	MOVIELOADER_CUBE_BOTTOM		5	//!< CUBE_BOTTOM
#define	MOVIELOADER_SPHERE			7	//!< SPHERE
